groups = {}
admins = {}
adminImmunities = {}
adminGroups = {}
adminsRawList = {}

ADMFLAG_RESERVATION = (1 << 0) -- a - Reserved Slot
ADMFLAG_GENERIC = (1 << 1)     -- b - Generic Admin; Access to u@
ADMFLAG_KICK = (1 << 2)        -- c - Kick players
ADMFLAG_BAN = (1 << 3)         -- d - Ban players
ADMFLAG_UNBAN = (1 << 4)       -- e - Unban players
ADMFLAG_SLAY = (1 << 5)        -- f - Slay
ADMFLAG_CHANGEMAP = (1 << 6)   -- g - Change map
ADMFLAG_CONVARS = (1 << 7)     -- h - Change server cvars
ADMFLAG_CONFIG = (1 << 8)      -- i - Executes commands over plugin specific config files
ADMFLAG_CHAT = (1 << 9)        -- j - Access to private say, center say, etc.
ADMFLAG_VOTE = (1 << 10)       -- k - Creates a vote on server
ADMFLAG_PASSWORD = (1 << 11)   -- l - Changes server's password
ADMFLAG_RCON = (1 << 12)       -- m - Use RCON commands
ADMFLAG_CHEATS = (1 << 13)     -- n - Changes sv_cheats and allows to use cheating commands (noclip, etc)
ADMFLAG_ROOT = (1 << 14)       -- z - Access to everything
ADMFLAG_CUSTOM1 = (1 << 15)    -- o - Custom Flag 1
ADMFLAG_CUSTOM2 = (1 << 16)    -- p - Custom Flag 2
ADMFLAG_CUSTOM3 = (1 << 17)    -- q - Custom Flag 3
ADMFLAG_CUSTOM4 = (1 << 18)    -- r - Custom Flag 4
ADMFLAG_CUSTOM5 = (1 << 19)    -- s - Custom Flag 5
ADMFLAG_CUSTOM6 = (1 << 20)    -- t - Custom Flag 6

flagsPermissions = {
    ["a"] = ADMFLAG_RESERVATION,
    ["b"] = ADMFLAG_GENERIC,
    ["c"] = ADMFLAG_KICK,
    ["d"] = ADMFLAG_BAN,
    ["e"] = ADMFLAG_UNBAN,
    ["f"] = ADMFLAG_SLAY,
    ["g"] = ADMFLAG_CHANGEMAP,
    ["h"] = ADMFLAG_CONVARS,
    ["i"] = ADMFLAG_CONFIG,
    ["j"] = ADMFLAG_CHAT,
    ["k"] = ADMFLAG_VOTE,
    ["l"] = ADMFLAG_PASSWORD,
    ["m"] = ADMFLAG_RCON,
    ["n"] = ADMFLAG_CHEATS,
    ["o"] = ADMFLAG_CUSTOM1,
    ["p"] = ADMFLAG_CUSTOM2,
    ["q"] = ADMFLAG_CUSTOM3,
    ["r"] = ADMFLAG_CUSTOM4,
    ["s"] = ADMFLAG_CUSTOM5,
    ["t"] = ADMFLAG_CUSTOM6,
    ["z"] = ADMFLAG_ROOT,
}